//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public long IdPedido { get; set; }
        public long Id { get; set; }
        public long IdProducto { get; set; }
        public long Cantidad { get; set; }
        public decimal ValorTotal { get; set; }
    }
}
